### ISSUE TITLE
Bug: lua 'popup' error when adding file without panel open

### ISSUE THREAD

**Issue by midekra** [jackMort/tide.nvim#2]
Hi, it seems the plugin has the ability to add files without having the panel open. Awesome. 
It does add the file, however, an error is displayed:

`E5108: Error executing lua: ./.local/share/nvim/lazy/tide.nvim/lua/tide/render.lua:71: attempt to index field 'popup' (a nil value)`

**Comment by jackMort** [comment]
good catch, it should works now.

**Comment by midekra** [comment]
Is just updated, but now i'm getting the following error during startup:
`.local/share/nvim/lazy/tide.nvim/lua/tide/state.lua:75: attempt to concatenate field 'state_filename' (a nil value)`

**Comment by midekra** [comment]
It seems the error only occurs when i'm opening a file which isn't part of a git branch.
